mp.messaging.outgoing.post-events-out.connector=smallrye-sns

mp.messaging.outgoing.post-events-out.topic.arn=${AXONPOSTS_EVENTS_TOPIC_ARN}

mp.messaging.incoming.post-completed-in.connector=smallrye-in-memory

quarkus.oidc.auth-server-url=${OIDC_ISSUER_URL}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}

quarkus.oidc.token.audience=${OIDC_CLIENT_ID}

quarkus.oidc.roles.role-claim-path=cognito:groups

axonposts.lambda.sqs.channel=post-completed-in
quarkus.lambda.handler=axon-sqs

axonposts.lambda.sqs.timeout=25s

quarkus.sns.region=${AWS_REGION:us-east-1}
quarkus.sqs.region=${AWS_REGION:us-east-1}
quarkus.sns.async-client.type=netty
quarkus.sqs.async-client.type=netty
quarkus.sns.aws.credentials.type=default
quarkus.sqs.aws.credentials.type=default

axonposts.graphql.sse.keep-alive=2s
