mp.messaging.outgoing.post-events-out.connector=smallrye-sns
mp.messaging.outgoing.post-events-out.topic.arn=${AXONPOSTS_EVENTS_TOPIC_ARN}

mp.messaging.incoming.post-precreated-in.connector=smallrye-in-memory
mp.messaging.incoming.post-changes-in.connector=smallrye-in-memory

axonposts.lambda.sqs.channel=${AXONPOSTS_LAMBDA_SQS_CHANNEL}
quarkus.lambda.handler=axon-sqs

axonposts.lambda.sqs.timeout=25s

quarkus.sns.region=${AWS_REGION:us-east-1}
quarkus.sqs.region=${AWS_REGION:us-east-1}
quarkus.sns.async-client.type=netty
quarkus.sqs.async-client.type=netty
quarkus.sns.aws.credentials.type=default
quarkus.sqs.aws.credentials.type=default
